// GENERATED from the fetch calls in each handler, then hand-corrected where a
// hostname cannot tell you the truth (a static table, a Gemini summary, or the
// Copernicus endpoint that derives its indices from the coordinates alone).
//
// Regenerate after adding an endpoint. A route missing here answers with
// kind "unavailable": a new endpoint is untrusted until its source is named.
import { declareSources } from "./provenance";

declareSources({
  "/api/agronomic-chilling-hours": { source: "Open-Meteo", url: "https://open-meteo.com", kind: "modeled", derivedFrom: "observations from Open-Meteo" },
  "/api/agronomic-evapotranspiration": { source: "Open-Meteo", url: "https://open-meteo.com", kind: "measured" },
  "/api/agronomic-nutrient-leaching": { source: "Open-Meteo", url: "https://open-meteo.com", kind: "measured" },
  "/api/agronomic-par-ppfd": { source: "Open-Meteo", url: "https://open-meteo.com", kind: "measured" },
  "/api/air-quality-aerosols": { source: "Open-Meteo Air Quality", url: "https://open-meteo.com", kind: "measured" },
  "/api/allergen-pollen-forecast": { source: "Open-Meteo Air Quality", url: "https://open-meteo.com", kind: "measured" },
  "/api/canopy-stomatal-conductance": { source: "Open-Meteo", url: "https://open-meteo.com", kind: "modeled", derivedFrom: "observations from Open-Meteo" },
  "/api/chat": { source: "Google Gemini", url: "https://ai.google.dev", kind: "modeled", derivedFrom: "the field context you supply" },
  "/api/client-ip-geolocation": { source: "ipapi.co", url: "https://ipapi.co", kind: "measured" },
  "/api/climate-projection": { source: "Open-Meteo Climate", url: "https://open-meteo.com", kind: "measured" },
  "/api/climatology-nasa": { source: "NASA POWER", url: "https://power.larc.nasa.gov", kind: "measured" },
  "/api/copernicus-sentinel-reflectance": { source: "coordinate hash", url: null, kind: "estimate", derivedFrom: "a sine of the latitude and longitude, not imagery" },
  "/api/crop-literature-handbooks": { source: "Open Library", url: "https://openlibrary.org", kind: "measured" },
  "/api/crop-lodging-shear": { source: "Open-Meteo", url: "https://open-meteo.com", kind: "modeled", derivedFrom: "observations from Open-Meteo" },
  "/api/crop-nutritive-macronutrients": { source: "static table in server.ts", url: null, kind: "reference" },
  "/api/crop-water-efficiency": { source: "Open-Meteo", url: "https://open-meteo.com", kind: "modeled", derivedFrom: "observations from Open-Meteo" },
  "/api/cropland-fire-risk": { source: "Open-Meteo", url: "https://open-meteo.com", kind: "measured" },
  "/api/detect-crop": { source: "Google Gemini", url: "https://ai.google.dev", kind: "modeled", derivedFrom: "regional climate and context" },
  "/api/dynamic-crops": { source: "static table in server.ts", url: null, kind: "reference" },
  "/api/ensemble-dispersion": { source: "Open-Meteo Ensemble", url: "https://open-meteo.com", kind: "measured" },
  "/api/environmental-telemetry": { source: "Open-Meteo Air Quality + Open-Meteo", url: "https://open-meteo.com", kind: "modeled", derivedFrom: "observations from Open-Meteo Air Quality + Open-Meteo" },
  "/api/flood-hydrology": { source: "Open-Meteo Flood", url: "https://open-meteo.com", kind: "measured" },
  "/api/frost-freeze-risk": { source: "Open-Meteo", url: "https://open-meteo.com", kind: "measured" },
  "/api/gbif-local-occurrences": { source: "GBIF", url: "https://www.gbif.org", kind: "measured" },
  "/api/gbif-species-suggest": { source: "GBIF", url: "https://www.gbif.org", kind: "measured" },
  "/api/gdacs-active-hazards": { source: "GDACS", url: "https://www.gdacs.org", kind: "measured" },
  "/api/global-greenhouse-gas-trends": { source: "Global Warming API", url: "https://global-warming.org", kind: "measured" },
  "/api/growing-degree-days": { source: "Open-Meteo", url: "https://open-meteo.com", kind: "measured" },
  "/api/health": { source: "this service", url: null, kind: "reference" },
  "/api/historical-reanalysis": { source: "Open-Meteo Archive", url: "https://open-meteo.com", kind: "measured" },
  "/api/iss-current-overhead": { source: "WhereTheISS.at", url: "https://wheretheiss.at", kind: "measured" },
  "/api/local-biodiversity": { source: "GBIF", url: "https://www.gbif.org", kind: "measured" },
  "/api/local-public-holidays": { source: "Nager.Date", url: "https://date.nager.at", kind: "measured" },
  "/api/macro-national": { source: "BigDataCloud + World Bank Open Data + Sunrise-Sunset.org + USGS Earthquake Catalog", url: "https://www.bigdatacloud.com", kind: "measured" },
  "/api/marine-hydrodynamics": { source: "Open-Meteo Marine", url: "https://open-meteo.com", kind: "measured" },
  "/api/nasa-eonet-active-events": { source: "NASA EONET", url: "https://eonet.gsfc.nasa.gov", kind: "measured" },
  "/api/noaa-space-weather-activity": { source: "NOAA SWPC", url: "https://www.swpc.noaa.gov", kind: "measured" },
  "/api/open-exchange-rates": { source: "Exchange Rate API", url: "https://www.exchangerate-api.com", kind: "measured" },
  "/api/openepi-forest-fire": { source: "OpenEPI", url: "https://openepi.io", kind: "measured" },
  "/api/openepi-soil": { source: "OpenEPI", url: "https://openepi.io", kind: "measured" },
  "/api/openmeteo-agri-soil": { source: "Open-Meteo", url: "https://open-meteo.com", kind: "measured" },
  "/api/openmeteo-boundary-layer": { source: "Open-Meteo", url: "https://open-meteo.com", kind: "measured" },
  "/api/openmeteo-geotech-elevation": { source: "Open-Meteo", url: "https://open-meteo.com", kind: "modeled", derivedFrom: "observations from Open-Meteo" },
  "/api/openmeteo-historical-archive": { source: "Open-Meteo Archive", url: "https://open-meteo.com", kind: "measured" },
  "/api/openmeteo-river-discharge": { source: "Open-Meteo Flood", url: "https://open-meteo.com", kind: "measured" },
  "/api/openmeteo-uv-radiation": { source: "Open-Meteo", url: "https://open-meteo.com", kind: "measured" },
  "/api/osm-local-natural-features": { source: "OpenStreetMap Overpass", url: "https://overpass-api.de", kind: "measured" },
  "/api/osm-reverse-geocode": { source: "BigDataCloud", url: "https://www.bigdatacloud.com", kind: "measured" },
  "/api/pest-disease-risk": { source: "Open-Meteo", url: "https://open-meteo.com", kind: "measured" },
  "/api/plant-dictionary-lookup": { source: "GBIF", url: "https://www.gbif.org", kind: "measured" },
  "/api/pollinator-activity": { source: "Open-Meteo", url: "https://open-meteo.com", kind: "measured" },
  "/api/predict": { source: "Google Gemini", url: "https://ai.google.dev", kind: "modeled", derivedFrom: "your own recorded field values" },
  "/api/regional-country-sovereign": { source: "REST Countries", url: "https://restcountries.com", kind: "measured" },
  "/api/soil-salinity-capillary": { source: "Open-Meteo", url: "https://open-meteo.com", kind: "measured" },
  "/api/solar-energy-potential": { source: "Open-Meteo", url: "https://open-meteo.com", kind: "measured" },
  "/api/sunrise-sunset-astronomy": { source: "Sunrise-Sunset.org", url: "https://sunrise-sunset.org", kind: "measured" },
  "/api/usda-crop-pricing": { source: "static table in server.ts", url: null, kind: "reference" },
  "/api/usgs-hydro-basin-watersheds": { source: "USGS National Hydrography Dataset", url: "https://hydro.nationalmap.gov", kind: "measured" },
  "/api/usgs-hydrology-waterwatch": { source: "USGS Water Services", url: "https://waterservices.usgs.gov", kind: "measured" },
  "/api/usgs-seismic-radial": { source: "USGS Earthquake Catalog", url: "https://earthquake.usgs.gov", kind: "measured" },
  "/api/weather-forecast": { source: "Open-Meteo", url: "https://open-meteo.com", kind: "measured" },
  "/api/worldbank-forest-coverage": { source: "BigDataCloud + World Bank Open Data", url: "https://www.bigdatacloud.com", kind: "measured" },
  "/api/soilgrids-properties": { source: "ISRIC SoilGrids", url: "https://soilgrids.org", kind: "measured" },
  "/api/nasa-power-daily": { source: "NASA POWER", url: "https://power.larc.nasa.gov", kind: "measured" },
  "/api/open-meteo-forecast": { source: "Open-Meteo", url: "https://open-meteo.com", kind: "measured" },
});
